# Fazer junção de datasets de acórdãos e lista do TRE

### Importação das libs

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

## Criar dataset de todas as decisões (acórdãos e pareceres)

In [2]:
caminho_dados = Path("../../data/raw/")
df_decisoes = pd.read_csv(caminho_dados/"tce_decisoes.csv", sep=";")

In [3]:
df_decisoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18538 entries, 0 to 18537
Data columns (total 18 columns):
cod_tce           18538 non-null object
assunto           16690 non-null object
tipo_processo     18538 non-null object
cod_ato           18538 non-null int64
ato               18538 non-null object
tipo_ato          18538 non-null object
peca              18538 non-null int64
caminho           18538 non-null object
conselheiro       15341 non-null object
municipio         15411 non-null object
ug                15411 non-null object
procurador        15268 non-null object
ano_exercicio     15377 non-null float64
texto             18496 non-null object
linhas            18535 non-null object
decisao_tipo      18484 non-null object
decisao_numero    18484 non-null object
decisao_ano       18484 non-null float64
dtypes: float64(2), int64(2), object(14)
memory usage: 2.5+ MB

In [4]:
df_decisoes.head()

,cod_tce,assunto,tipo_processo,cod_ato,ato,tipo_ato,peca,caminho,conselheiro,municipio,ug,procurador,ano_exercicio,texto,linhas,decisao_tipo,decisao_numero,decisao_ano
0,000038/2014,REPRESENTAÇÃO REF. À IRREGULARIDADES NA CONTRA...,CONTROLE SOCIAL - REPRESENTAÇÃO,350333,ACOCAM - GABELARDO - 166/2014,ACÓRDÃO DE CÂMARA,19,/2014/11/623484/9/2/795temp/ACOCAM.pdf,ABELARDO PIO VILANOVA E SILVA,Colônia do Gurguéia,P. M. DE COLONIA DO GURGUEIA,LEANDRO MACIEL DO NASCIMENTO,2013.0,ACÓRDÃO 1397/14\nPROCESSO TC nº 00003814\nASSU...,"[{'page': 1, 'x0': 257, 'x1': 369, 'bottom': 1...",acordao,1397,2014.0
1,000040/2014,REPRESENTAÇÃO REF. À IRREGULARIDADES NA ADMINI...,CONTROLE SOCIAL - REPRESENTAÇÃO,302399,ACOCAM - GABELARDO - 122/2014,ACÓRDÃO DE CÂMARA,21,/2014/09/623486/9/2/965temp/ACOCAM.pdf,ABELARDO PIO VILANOVA E SILVA,Colônia do Gurguéia,P. M. DE COLONIA DO GURGUEIA,LEANDRO MACIEL DO NASCIMENTO,2013.0,ACÓRDÃO 940/14\nPROCESSO TC nº 000040/14\nASSU...,"[{'page': 1, 'x0': 260, 'x1': 366, 'bottom': 1...",acordao,940,2014.0
2,000004/2020,APOSENTADORIA,INATIVAÇÃO - APOSENTADORIA,2460076,ACOCAM - AUD-JAYLSO - 1577/2020,ACÓRDÃO DE CÂMARA,9,/2020/03//770552/16/2/29032020_102735_57C73E39...,JAYLSON FABIANH LOPES CAMPELO,Itainópolis,FMPS-FUNDO MUNIC. DE PREVIDÊNCIA SOCIAL DE ITA...,MARCIO ANDRE MADEIRA DE VASCONCELOS,2020.0,ACÓRDÃO Nº 356/2020\nPROCESSO TC/000004/2020\n...,"[{'page': 1, 'x0': 230, 'x1': 356, 'bottom': 1...",acordao,356,2020.0
3,000115/2017,"DENÚNCIA REF. IRREGULARIDADES NA SESAPI, EXERC...",CONTROLE SOCIAL - DENÚNCIA,1353881,ACOPLE - G.KDE - 188/2017,ACÓRDÃO DO PLENO,34,/2017/08/688319/173/3/478temp/ACOPLE.pdf,NaN,NaN,NaN,NaN,NaN,ACÓRDÃO Nº 2.283/2017 (fl. 01)\n\n\nPROCESSO: ...,"[{'page': 1, 'x0': 229, 'x1': 397, 'bottom': 1...",acordao,2283,2017.0
4,000135/2020,RECURSO DE RECONSIDERAÇÃO REF. AO TC/005130/2015,DOS RECURSOS - RECURSO DE RECONSIDERAÇÃO,2462530,ACOCAM - G.WA - 690/2020,ACÓRDÃO DE CÂMARA,15,/2020/03//770683/8/2/17032020_095623_46033325D...,WALTANIA MARIA NOGUEIRA DE SOUSA LEAL ALVARENGA,Nazária,CAMARA DE NAZARIA,JOSE ARAUJO PINHEIRO JUNIOR,2015.0,ACÓRDÃO Nº 317/2020\nPROCESSO: TC/000135/2020\...,"[{'page': 1, 'x0': 245, 'x1': 377, 'bottom': 1...",acordao,317,2020.0

## Criar dataset de lista do TRE

In [5]:
df_tre = pd.read_csv(caminho_dados/"lista-tre-com-protocolo.csv", sep=";")

In [6]:
df_tre.head()

,ANO_DO_JULGAMENTO,DECISAO,DATA_DO_JULGAMENTO,PROCESSO,MUNICIPIO_ENTE,ORGAO,EXERCICIO,GESTOR,CPF,RESULTADO,DATA_DO_TRANSITO_EM_JULGADO,DATA_DA_INCLUSAO_NA_LISTA,COD_TCE,DECISAO_NUMERO,DECISAO_ANO
0,2011.0,546/11,2011-05-19 00:00:00,TC-E 40.660/09,ALAGOINHA DO PIAUÍ,CÂMARA MUNICIPAL,2008,ABELARDO ANTÔNIO DE SÁ,NaN,IRREGULARIDADE,NaN,NaN,040660/2009,546,2011.0
1,2011.0,1434/11,2011-12-01 00:00:00,TC-E 15.100/10,LAGOA DO SÍTIO,CÂMARA MUNICIPAL,2009,ABIMAR SOARES LIMA VERDE,NaN,IRREGULARIDADE,NaN,NaN,015100/2010,1434,2011.0
2,2011.0,47/11,2011-01-13 00:00:00,TC-E 22.557/09,RIBEIRA DO PIAUÍ,FMS,2008,ADÃO LIRA LEAL,NaN,IRREGULARIDADE,NaN,NaN,022557/2009,47,2011.0
3,2011.0,1458/11,2011-12-07 00:00:00,TC-E 16.248/10,RIBEIRA DO PIAUÍ,FMS,2009,ADÃO LIRA LEAL,NaN,IRREGULARIDADE,NaN,NaN,016248/2010,1458,2011.0
4,2011.0,733/10,2011-06-16 00:00:00,TC-E 12.462/08,COCAL,CÂMARA MUNICIPAL,2007,ADERSON NOGUEIRA RAMOS,NaN,IRREGULARIDADE,NaN,NaN,012462/2008,733,2010.0

In [7]:
df_tre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2333 entries, 0 to 2332
Data columns (total 15 columns):
ANO_DO_JULGAMENTO              2333 non-null float64
DECISAO                        2333 non-null object
DATA_DO_JULGAMENTO             2333 non-null object
PROCESSO                       2333 non-null object
MUNICIPIO_ENTE                 2326 non-null object
ORGAO                          2331 non-null object
EXERCICIO                      2333 non-null object
GESTOR                         2333 non-null object
CPF                            1662 non-null object
RESULTADO                      2333 non-null object
DATA_DO_TRANSITO_EM_JULGADO    135 non-null object
DATA_DA_INCLUSAO_NA_LISTA      135 non-null object
COD_TCE                        2332 non-null object
DECISAO_NUMERO                 2330 non-null object
DECISAO_ANO                    2330 non-null float64
dtypes: float64(2), object(13)
memory usage: 273.5+ KB

In [8]:
len(df_tre['COD_TCE'].unique())

865

In [9]:
processos_qtde = df_tre['COD_TCE'].value_counts()
processos_qtde[processos_qtde > 1]

016269/2010    15
018349/2012    12
022907/2011    12
053499/2009    11
022563/2011    11
               ..
003059/2016     2
013756/2011     2
014301/2011     2
012907/2011     2
003038/2016     2
Name: COD_TCE, Length: 508, dtype: int64

In [10]:
df_tre['RESULTADO'].value_counts()

IRREGULARIDADE               1702
REPROVAÇÃO                    391
Irregularidade                153
Irregular                      46
Reprovação                     33
PELA REPROVAÇÃO                 2
REPROVAÇÃO                      2
RECOMENDANDO A REPROVAÇÃO       1
IRREGUARIDADE                   1
 IRREGULARIDADE                 1
IRREAGULARIDADE                 1
Name: RESULTADO, dtype: int64

In [11]:
df_tre['DECISAO_NUMERO'].describe()

count     2330
unique    1387
top       1236
freq        13
Name: DECISAO_NUMERO, dtype: object

In [12]:
df_tre[df_tre['DECISAO_ANO'].isna()]

,ANO_DO_JULGAMENTO,DECISAO,DATA_DO_JULGAMENTO,PROCESSO,MUNICIPIO_ENTE,ORGAO,EXERCICIO,GESTOR,CPF,RESULTADO,DATA_DO_TRANSITO_EM_JULGADO,DATA_DA_INCLUSAO_NA_LISTA,COD_TCE,DECISAO_NUMERO,DECISAO_ANO
861,2013.0,1428,2013-06-26 00:00:00,TC-E 014.408/11,SEBASTIÃO BARROS,SECRETARIA MUNICIPAL DE EDUCAÇÃO,2010,HÉRIKA DANIELLA DE CARVALHO E GUEDES,991.971.703-72,IRREGULARIDADE,NaN,NaN,014408/2011,NaN,NaN
1073,2014.0,PARECER 90114,2014-09-02 00:00:00,TCE 16228/2012,OLHO D`AGUA DO PIAUI,PREFEITURA,2011,ANTONIO LEAL DA SILVA,184.737.253-87,REPROVAÇÃO,NaN,NaN,016228/2012,NaN,NaN
1242,2015.0,206-A,2015-10-28 00:00:00,TC/52818/2012,BATALHA,PREFEITURA MUNICIPAL - GOVERNO,2012,AMARO JOSÉ DE FREITAS MELO,111.992.455-34,REPROVAÇÃO,NaN,NaN,052818/2012,NaN,NaN

In [13]:
df_decisoes[df_decisoes['cod_tce'] == '052818/2012']

Empty DataFrame
Columns: [cod_tce, assunto, tipo_processo, cod_ato, ato, tipo_ato, peca, caminho, conselheiro, municipio, ug, procurador, ano_exercicio, texto, linhas, decisao_tipo, decisao_numero, decisao_ano]
Index: []

In [14]:
df_tre[df_tre['DECISAO_NUMERO'].notna()]['DECISAO_NUMERO'].apply(len).value_counts()

4    1047
3    1031
2     213
1      19
6      15
5       5
Name: DECISAO_NUMERO, dtype: int64

## Juntar os datasets

In [15]:
df_merge = df_tre.merge(df_decisoes, \
                    left_on=['COD_TCE', 'DECISAO_NUMERO', 'DECISAO_ANO'], \
                    right_on=['cod_tce', 'decisao_numero', 'decisao_ano'])

In [16]:
df_merge.head()

,ANO_DO_JULGAMENTO,DECISAO,DATA_DO_JULGAMENTO,PROCESSO,MUNICIPIO_ENTE,ORGAO,EXERCICIO,GESTOR,CPF,RESULTADO,...,conselheiro,municipio,ug,procurador,ano_exercicio,texto,linhas,decisao_tipo,decisao_numero,decisao_ano
0,2014.0,100/2014,2014-09-17 00:00:00,TC/013381/2013,VÁRZEA GRANDE,PREFEITURA - GOVERNO,2011,LUÍS NUNES RIBEIRO FILHO,085.986.338-79,REPROVAÇÃO,...,LILIAN DE ALMEIDA VELOSO NUNES MARTINS,Várzea Grande,P. M. DE VARZEA GRANDE,MÁRCIO ANDRÉ MADEIRA DE VASCONCELOS,2011.0,PARECER PRÉVIO N°. 100/2014\n\n\nPROCESSO TC N...,"[{'page': 1, 'x0': 206, 'x1': 421, 'bottom': 1...",parecer,100,2014.0
1,2014.0,1164/2014,2014-09-17 00:00:00,TC/013381/2013,VÁRZEA GRANDE,PREFEITURA GESTÃO,2011,LUÍS NUNES RIBEIRO FILHO,085.986.338-79,IRREGULARIDADE,...,LILIAN DE ALMEIDA VELOSO NUNES MARTINS,Várzea Grande,P. M. DE VARZEA GRANDE,MÁRCIO ANDRÉ MADEIRA DE VASCONCELOS,2011.0,ACORDÃO N°. 1.164/2014\n\nPROCESSO: TC- E N° 0...,"[{'page': 1, 'x0': 248, 'x1': 378, 'bottom': 1...",acordao,1164,2014.0
2,2015.0,2707/2015,2015-11-25 00:00:00,010297/2015,BARRAS,COORD. REGIONAL DE SAÚDE II,2013,ANA MARIA DE SOUSA,396.067.243-87,IRREGULARIDADE,...,ALISSON FELIPE DE ARAUJO,Barras,COORD. REG. SAUDE II - BARRAS,JOSE ARAUJO PINHEIRO JUNIOR,2013.0,ACÓRDÃO Nº. 2707/15\n\nEstado do Piauí II.Coor...,"[{'page': 1, 'x0': 276, 'x1': 370, 'bottom': 1...",acordao,2707,2015.0
3,2015.0,165/15,2015-02-03 00:00:00,8519/2013,CAMPO ALEGRE DO FIDALGO,FUNDEB,2011,LEÔNCIO JOÃO DA MATA,463.077.963-91,IRREGULARIDADE,...,OLAVO REBELO DE CARVALHO FILHO,Campo Alegre do Fidalgo,P. M. DE CAMPO ALEGRE DO FIDALGO,PLÍNIO VALENTE RAMOS NETO,2011.0,ACÓRDÃO Nº. 165/2015\n\n\nPrestação de Contas ...,"[{'page': 1, 'x0': 233, 'x1': 394, 'bottom': 1...",acordao,165,2015.0
4,2015.0,PARECER 14/15,2015-02-03 00:00:00,8519/2013,CAMPO ALEGRE DO FIDALGO,PREFEITURA,2011,ISRAEL ODÍLIO DA MATA,156.526.103-87,REPROVAÇÃO,...,OLAVO REBELO DE CARVALHO FILHO,Campo Alegre do Fidalgo,P. M. DE CAMPO ALEGRE DO FIDALGO,PLÍNIO VALENTE RAMOS NETO,2011.0,PARECER PRÉVIO Nº. 14/2015\n\n\n\nPrestação de...,"[{'page': 1, 'x0': 210, 'x1': 417, 'bottom': 1...",parecer,14,2015.0

In [17]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 519 entries, 0 to 518
Data columns (total 33 columns):
ANO_DO_JULGAMENTO              519 non-null float64
DECISAO                        519 non-null object
DATA_DO_JULGAMENTO             519 non-null object
PROCESSO                       519 non-null object
MUNICIPIO_ENTE                 510 non-null object
ORGAO                          518 non-null object
EXERCICIO                      519 non-null object
GESTOR                         519 non-null object
CPF                            518 non-null object
RESULTADO                      519 non-null object
DATA_DO_TRANSITO_EM_JULGADO    128 non-null object
DATA_DA_INCLUSAO_NA_LISTA      126 non-null object
COD_TCE                        519 non-null object
DECISAO_NUMERO                 519 non-null object
DECISAO_ANO                    519 non-null float64
cod_tce                        519 non-null object
assunto                        517 non-null object
tipo_processo                  519 non-null object
cod_ato                        519 non-null int64
ato                            519 non-null object
tipo_ato                       519 non-null object
peca                           519 non-null int64
caminho                        519 non-null object
conselheiro                    480 non-null object
municipio                      480 non-null object
ug                             480 non-null object
procurador                     480 non-null object
ano_exercicio                  480 non-null float64
texto                          519 non-null object
linhas                         519 non-null object
decisao_tipo                   519 non-null object
decisao_numero                 519 non-null object
decisao_ano                    519 non-null float64
dtypes: float64(4), int64(2), object(27)
memory usage: 137.9+ KB

In [18]:
df_merge[['DECISAO', 'COD_TCE', 'RESULTADO', 'cod_tce', 'peca', 'decisao_tipo', 'decisao_numero', 'decisao_ano', \
          'assunto', 'tipo_processo', 'tipo_ato', 'conselheiro', 'texto']]

,DECISAO,COD_TCE,RESULTADO,cod_tce,peca,decisao_tipo,decisao_numero,decisao_ano,assunto,tipo_processo,tipo_ato,conselheiro,texto
0,100/2014,013381/2013,REPROVAÇÃO,013381/2013,40,parecer,100,2014.0,"TOMADA DE CONTAS DE GESTÃO, EXERCÍCIO 2011",CONTAS - TOMADA DE CONTAS,ACÓRDÃO DE CÂMARA,LILIAN DE ALMEIDA VELOSO NUNES MARTINS,PARECER PRÉVIO N°. 100/2014\n\n\nPROCESSO TC N...
1,1164/2014,013381/2013,IRREGULARIDADE,013381/2013,41,acordao,1164,2014.0,"TOMADA DE CONTAS DE GESTÃO, EXERCÍCIO 2011",CONTAS - TOMADA DE CONTAS,ACÓRDÃO DE CÂMARA,LILIAN DE ALMEIDA VELOSO NUNES MARTINS,ACORDÃO N°. 1.164/2014\n\nPROCESSO: TC- E N° 0...
2,2707/2015,010297/2015,IRREGULARIDADE,010297/2015,27,acordao,2707,2015.0,TOMADA DE CONTAS - EXERCÍCIO 2013,CONTAS - TOMADA DE CONTAS,ACÓRDÃO DE CÂMARA,ALISSON FELIPE DE ARAUJO,ACÓRDÃO Nº. 2707/15\n\nEstado do Piauí II.Coor...
3,165/15,008519/2013,IRREGULARIDADE,008519/2013,30,acordao,165,2015.0,"PRESTAÇÃO DE CONTAS DE GESTÃO, EXERCÍCIO 2011 ...",CONTAS - CONTAS DE GESTÃO,ACÓRDÃO DE CÂMARA,OLAVO REBELO DE CARVALHO FILHO,ACÓRDÃO Nº. 165/2015\n\n\nPrestação de Contas ...
4,PARECER 14/15,008519/2013,REPROVAÇÃO,008519/2013,27,parecer,14,2015.0,"PRESTAÇÃO DE CONTAS DE GESTÃO, EXERCÍCIO 2011 ...",CONTAS - CONTAS DE GESTÃO,PARECER PRÉVIO,OLAVO REBELO DE CARVALHO FILHO,PARECER PRÉVIO Nº. 14/2015\n\n\n\nPrestação de...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,179/2020 (R.R),019012/2018,IRREGULARIDADE,019012/2018,25,acordao,179,2020.0,RECURSO DE RECONSIDERAÇAO REF. AO TC/002974/20...,DOS RECURSOS - RECURSO DE RECONSIDERAÇÃO,ACÓRDÃO DO PLENO,NaN,ACÓRDÃO N.º 179/2020\nEMENTA. RECURSO DE RECON...
515,180/2020 (R.R),019014/2018,IRREGULARIDADE,019014/2018,25,acordao,180,2020.0,RECURSO DE RECONSIDERAÇAO REF. AO TC/002974/20...,DOS RECURSOS - RECURSO DE RECONSIDERAÇÃO,ACÓRDÃO DO PLENO,NaN,ACÓRDÃO N.º 180/2020\nEMENTA. RECURSO DE RECON...
516,267/2020 (R.R),019016/2018,REPROVAÇÃO,019016/2018,29,acordao,267,2020.0,RECURSO DE RECONSIDERAÇAO REF. AO TC/002974/20...,DOS RECURSOS - RECURSO DE RECONSIDERAÇÃO,ACÓRDÃO DO PLENO,NaN,ACÓRDÃO N.º 267/20\nEMENTA. RECURSO DE RECONSI...
517,181/2020 (R.R),019015/2018,IRREGULARIDADE,019015/2018,25,acordao,181,2020.0,RECURSO DE RECONSIDERAÇAO REF. AO TC/002974/20...,DOS RECURSOS - RECURSO DE RECONSIDERAÇÃO,ACÓRDÃO DO PLENO,NaN,ACÓRDÃO N.º 181/2020\nEMENTA. RECURSO DE RECON...
518,331/2020 (R.R),021496/2019,IRREGULARIDADE,021496/2019,13,acordao,331,2020.0,RECURSO DE RECONSIDERAÇÃO REF. AO TC/005371/2015.,DOS RECURSOS - RECURSO DE RECONSIDERAÇÃO,ACÓRDÃO DO PLENO,NaN,ACÓRDÃO N.º 331/2020\nEMENTA. RECURSO DE RECON...

In [19]:
df_merge[df_merge['cod_tce']=='013381/2013']

,ANO_DO_JULGAMENTO,DECISAO,DATA_DO_JULGAMENTO,PROCESSO,MUNICIPIO_ENTE,ORGAO,EXERCICIO,GESTOR,CPF,RESULTADO,...,conselheiro,municipio,ug,procurador,ano_exercicio,texto,linhas,decisao_tipo,decisao_numero,decisao_ano
0,2014.0,100/2014,2014-09-17 00:00:00,TC/013381/2013,VÁRZEA GRANDE,PREFEITURA - GOVERNO,2011,LUÍS NUNES RIBEIRO FILHO,085.986.338-79,REPROVAÇÃO,...,LILIAN DE ALMEIDA VELOSO NUNES MARTINS,Várzea Grande,P. M. DE VARZEA GRANDE,MÁRCIO ANDRÉ MADEIRA DE VASCONCELOS,2011.0,PARECER PRÉVIO N°. 100/2014\n\n\nPROCESSO TC N...,"[{'page': 1, 'x0': 206, 'x1': 421, 'bottom': 1...",parecer,100,2014.0
1,2014.0,1164/2014,2014-09-17 00:00:00,TC/013381/2013,VÁRZEA GRANDE,PREFEITURA GESTÃO,2011,LUÍS NUNES RIBEIRO FILHO,085.986.338-79,IRREGULARIDADE,...,LILIAN DE ALMEIDA VELOSO NUNES MARTINS,Várzea Grande,P. M. DE VARZEA GRANDE,MÁRCIO ANDRÉ MADEIRA DE VASCONCELOS,2011.0,ACORDÃO N°. 1.164/2014\n\nPROCESSO: TC- E N° 0...,"[{'page': 1, 'x0': 248, 'x1': 378, 'bottom': 1...",acordao,1164,2014.0

### Verificar consistência dos dados de resultados

In [20]:
df_merge['RESULTADO'].value_counts()

IRREGULARIDADE    407
REPROVAÇÃO        109
REPROVAÇÃO          2
IRREGUARIDADE       1
Name: RESULTADO, dtype: int64

In [21]:
df_merge.loc[df_merge['RESULTADO'] == 'IRREGUARIDADE', ['RESULTADO']] = 'IRREGULARIDADE'

In [22]:
df_merge['RESULTADO'].value_counts()

IRREGULARIDADE    408
REPROVAÇÃO        109
REPROVAÇÃO          2
Name: RESULTADO, dtype: int64

In [23]:
df_merge['RESULTADO'] = df_merge['RESULTADO'].apply(lambda x: x.strip())

In [24]:
df_merge['RESULTADO'].value_counts()

IRREGULARIDADE    408
REPROVAÇÃO        111
Name: RESULTADO, dtype: int64

In [25]:
# Análise de resultados por tipo de ato
df_merge[['tipo_ato', 'RESULTADO', 'cod_tce']].groupby(['tipo_ato', 'RESULTADO']).count()

                                  cod_tce
tipo_ato          RESULTADO
ACÓRDÃO           IRREGULARIDADE      109
                  REPROVAÇÃO            4
ACÓRDÃO DE CÂMARA IRREGULARIDADE      263
                  REPROVAÇÃO           11
ACÓRDÃO DO PLENO  IRREGULARIDADE       35
                  REPROVAÇÃO            8
PARECER PRÉVIO    IRREGULARIDADE        1
                  REPROVAÇÃO           88

In [26]:
# Análise de resultados por tipo de decisão
df_merge[['decisao_tipo', 'RESULTADO', 'cod_tce']].groupby(['decisao_tipo', 'RESULTADO']).count()

                             cod_tce
decisao_tipo RESULTADO
acordao      IRREGULARIDADE      406
             REPROVAÇÃO           11
parecer      IRREGULARIDADE        2
             REPROVAÇÃO          100

In [27]:
# Análise de resultados por tipo de processo
df_merge[['tipo_processo', 'RESULTADO', 'cod_tce']].groupby(['tipo_processo', 'RESULTADO']).count()

                                                         cod_tce
tipo_processo                            RESULTADO
CONTAS - CONTAS DE GESTÃO                IRREGULARIDADE       40
                                         REPROVAÇÃO           83
CONTAS - TOMADA DE CONTAS                IRREGULARIDADE       16
                                         REPROVAÇÃO            7
CONTAS - TOMADA DE CONTAS ESPECIAL       IRREGULARIDADE       22
DA REVISÃO - PEDIDO DE REVISÃO           IRREGULARIDADE        4
DOS RECURSOS - RECURSO DE RECONSIDERAÇÃO IRREGULARIDADE       28
                                         REPROVAÇÃO           10
PRESTAÇÃO DE CONTAS                      IRREGULARIDADE       61
                                         REPROVAÇÃO            4
PRESTAÇÃO DE CONTAS - PROVISÓRIO         IRREGULARIDADE      237
                                         REPROVAÇÃO            7

### Procurar itens da lista não encontrados nas decisões

In [28]:
df_tre_l = df_tre.merge(df_decisoes, how="left", \
                    left_on=['COD_TCE', 'DECISAO_NUMERO', 'DECISAO_ANO'], \
                    right_on=['cod_tce', 'decisao_numero', 'decisao_ano'])

In [30]:
# Não relacionados
df_tre_l = df_tre_l[df_tre_l['cod_tce'].isna()]
df_tre_l.shape

(1851, 33)

In [31]:
df_tre_l.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1851 entries, 0 to 2363
Data columns (total 33 columns):
ANO_DO_JULGAMENTO              1851 non-null float64
DECISAO                        1851 non-null object
DATA_DO_JULGAMENTO             1851 non-null object
PROCESSO                       1851 non-null object
MUNICIPIO_ENTE                 1851 non-null object
ORGAO                          1850 non-null object
EXERCICIO                      1851 non-null object
GESTOR                         1851 non-null object
CPF                            1181 non-null object
RESULTADO                      1851 non-null object
DATA_DO_TRANSITO_EM_JULGADO    13 non-null object
DATA_DA_INCLUSAO_NA_LISTA      15 non-null object
COD_TCE                        1850 non-null object
DECISAO_NUMERO                 1848 non-null object
DECISAO_ANO                    1848 non-null float64
cod_tce                        0 non-null object
assunto                        0 non-null object
tipo_processo                  0 non-null object
cod_ato                        0 non-null float64
ato                            0 non-null object
tipo_ato                       0 non-null object
peca                           0 non-null float64
caminho                        0 non-null object
conselheiro                    0 non-null object
municipio                      0 non-null object
ug                             0 non-null object
procurador                     0 non-null object
ano_exercicio                  0 non-null float64
texto                          0 non-null object
linhas                         0 non-null object
decisao_tipo                   0 non-null object
decisao_numero                 0 non-null object
decisao_ano                    0 non-null float64
dtypes: float64(6), object(27)
memory usage: 491.7+ KB

In [32]:
df_tre_l[['ANO_DO_JULGAMENTO', 'DECISAO', 'PROCESSO', 'COD_TCE']].sort_values('ANO_DO_JULGAMENTO', ascending=False)

      ANO_DO_JULGAMENTO             DECISAO        PROCESSO      COD_TCE
2348             2020.0            137/2020  TC/010097/2020  010097/2020
2253             2019.0  1.206-A/2019 (R.R)  TC/019419/2018  019419/2018
2307             2019.0          1.858/2019  TC/006166/2019  006166/2019
2279             2019.0        P.P 089/2019  TC/003074/2019  003074/2019
2267             2019.0       P.P 065/2019   TC/003054/2016  003054/2016
...                 ...                 ...             ...          ...
274              2011.0              201/11  TC-E 53.494/09  053494/2009
275              2011.0              201/11  TC-E 53.494/09  053494/2009
276              2011.0              354/11  TC-E 27.252/09  027252/2009
277              2011.0              354/11  TC-E 27.252/09  027252/2009
0                2011.0              546/11  TC-E 40.660/09  040660/2009

[1851 rows x 4 columns]

In [33]:
# Verificar alguns exemplos de registros não relacionados
df_decisoes[df_decisoes['cod_tce'] == '019419/2018'][['cod_tce', 'decisao_tipo', 'decisao_numero', 'decisao_ano']]

          cod_tce decisao_tipo decisao_numero  decisao_ano
9892  019419/2018      acordao           1206       2019.0

In [38]:
df_tre_l.merge(df_decisoes, how="inner", left_on=['COD_TCE'], right_on=['cod_tce']\
              ).sort_values('ANO_DO_JULGAMENTO', ascending=False)\
    [['DECISAO', 'DECISAO_NUMERO', 'DECISAO_ANO', 'COD_TCE', \
      'decisao_tipo_y', 'decisao_numero_y', 'decisao_ano_y', 'peca_y', 'texto_y']]

,DECISAO,DECISAO_NUMERO,DECISAO_ANO,COD_TCE,decisao_tipo_y,decisao_numero_y,decisao_ano_y,peca_y,texto_y
1116,P.P 065/2019,65,2019.0,003054/2016,acordao,3082,2017.0,98,PARECER PRÉVIO Nº 65/2019\n\nPROCESSO TC/00305...
1103,P.P 065/2019,65,2019.0,003054/2016,acordao,870,2019.0,120,ACÓRDÃO Nº 870/2019\nPROCESSO TC/003054/2016\n...
1091,014/19,14,2019.0,005287/2015,acordao,208,2019.0,48,ACÓRDÃO Nº 208/2019\n\n\nPROCESSO: TC/005287/2...
1092,014/19,14,2019.0,005287/2015,acordao,209,2019.0,49,ACÓRDÃO Nº 209/2019\n\n\nPROCESSO: TC/005287/2...
1093,014/19,14,2019.0,005287/2015,acordao,210,2019.0,50,ACÓRDÃO Nº 210/2019\n\n\nPROCESSO: TC/005287/2...
...,...,...,...,...,...,...,...,...,...
3,880/14,880,2014.0,053058/2012,acordao,854,2015.0,29,ACORDÃO N°. 854/2015\n\nPROCESSO: TC 52909/12....
1,880/14,880,2014.0,053058/2012,acordao,853,2015.0,28,ACORDÃO N°. 853/2015\n\nPROCESSO: TC 52909/12....
5,880/14,880,2014.0,053058/2012,acordao,851,2015.0,26,ACORDÃO N°. 851/2015\n\nPROCESSO: TC 52909/12....
6,880/14,880,2014.0,053058/2012,parecer,81,2015.0,25,PARECER PRÉVIO N° 81/2015\n\n\nPROCESSO TC/ 52...
0,880/14,880,2014.0,053058/2012,acordao,852,2015.0,27,ACORDÃO N°. 852/2015\n\nPROCESSO: TC 52909/12....

In [ ]:
df_decisoes[df_decisoes['decisao_numero'].notna()]['decisao_numero'].apply(lambda x: int(x) if x.isnumeric() else x)

In [ ]:
df_tre[df_tre['COD_TCE']=='002996/2016']

### Itens da Lista que número do processo precisam ser checados